<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Authenticate' => '',
    'Connect TheMovieDB' => '',
    'Email' => '',
    'Name' => '',
    'Password (only change to set a new one)' => '',
    'Preferences' => '',
    'Public profile' => '',
    'Reconnect TheMovieDB' => '',
    'Save Settings' => '',
    'Settings saved.' => '',
    'Sync' => '',
    'The timezone does not exist!' => '',
    'Your Account' => '',
    'Your accounts are synced periodically every 24 hours, but you can start syncing your ratings immediately.' => '',
];
