<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'We currently cannot recommend any new shows for you! Try to subscribe to more shows you like.' => '',
    'You are not subscribe to a TV Show! Start with searching for your favorites.' => '',
    'Your archive is empty! Add TV Shows which are not in production anymore or you are currently not watching.' => '',
    '{name} TV Shows' => '',
];
