language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - node_modules

install:
  - composer self-update
  - npm install -g bower
  - composer global require "fxp/composer-asset-plugin:1.1.*"
  - composer install --dev --no-progress
  - npm install
  - echo "<?php return '/web/index-test.php';" >> ./tests/codeception/_localurl.php
  - 'cd tests && ./../vendor/bin/codecept build'

before_script: mysql -e 'create database testing;'

script: './../vendor/bin/codecept run unit'
