#!/usr/bin/env php
<?php
$env = isset($_SERVER['APPLICATION_ENV']) ? $_SERVER['APPLICATION_ENV'] : 'development';

if ($env == 'development') {
	defined('YII_DEBUG') or define('YII_DEBUG', true);
}

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/' . $env . '/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
