<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cast' => '',
    'Crew' => '',
    'Edit missing information on The Movie Database' => '',
    'Label `{name}` as seen' => '',
    'Label `{name}` as unseen' => '',
    'Label complete season as seen' => '',
    'Login to label `{name}` as seen' => '',
    'Please subscribe to the show before labeling episodes as seen.' => '',
    'Subscribe to the show for labeling `{name}` as seen' => '',
    'TV Shows' => '',
    'Videos' => '',
    'Voting' => '',
    '{average}/10 ({count} Votes)' => '',
    '{name} as {character}' => '',
];
