<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Application successfully updated.' => '',
    'Application {name}' => '',
    'Applications' => '',
    'Callback URL' => '',
    'Callback where the user should be redirected after authenticating.' => '',
    'Client ID' => '',
    'Create Applications' => '',
    'Create application' => '',
    'Created at' => '',
    'Delete application' => '',
    'Description' => '',
    'Fully qualified url to your website. The website will be displayed next to the description.' => '',
    'ID' => '',
    'Name' => '',
    'Regenerate API keys' => '',
    'Secret' => '',
    'Show secret' => '',
    'The consumer application could not be found or you are not the owner of the application.' => '',
    'The description will be visible to users. Between 10 and 256 characters.' => '',
    'The name of the application will be visible to users. 32 characters max.' => '',
    'Update' => '',
    'Update application' => '',
    'Update application {name}' => '',
    'Update details' => '',
    'Updated at' => '',
    'User' => '',
    'Website' => '',
    'You did not create a application yet.' => '',
    'You successfully deleted the application.' => '',
    'Your applications' => '',
];
