<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Api Documentation' => '',
    'Overview' => '',
    'SEEN uses <a href="{oauthUrl}">OAuth2</a> to authorize the client. Therefore you have to <a href="{consumerUrl}">register an application</a> to obtain your key and secret.' => '',
    'The documentation is available at <a href="{url}">apiary</a>. With apiary you are able to use a proxy server to record and inspect your requests. The proxy server is only for development purposes. For production environments please use the real url.' => '',
];
