<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'An unknown error occured! Please try again later.' => '',
    'Error {code}' => '',
    'Guest' => '',
    'The site you were looking for does not exist! Please contact us if you think this was our mistake.' => '',
    'There was an error while processing your request! We got informed and are trying to fix this error as soon as possible.' => '',
    'Unknown' => '',
];
