<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All Languages' => '',
    'All auth items' => '',
    'Created at' => '',
    'Deleted at' => '',
    'English name' => '',
    'Hide' => '',
    'ID' => '',
    'ISO 639-1' => '',
    'Language {name}' => '',
    'Languages' => '',
    'Name' => '',
    'Popular movies updated at' => '',
    'Popular shows updated at' => '',
    'RTL' => '',
    'Save Language' => '',
    'The language #{$id} does not exist' => '',
    'Update' => '',
    'Update {name}' => '',
    'Updated at' => '',
];
