<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Adult' => '',
    'Average vote' => '',
    'Backdrop path' => '',
    'Budget' => '',
    'Could not load movie! Please try again later.' => '',
    'Created at' => '',
    'Deleted at' => '',
    'Genres' => '',
    'Homepage' => '',
    'ID' => '',
    'IMDB ID' => '',
    'Language ID' => '',
    'Minutes' => '',
    'Original Title' => '',
    'Overview' => '',
    'Popularity' => '',
    'Poster path' => '',
    'Rate with {count} stars' => '',
    'Release date' => '',
    'Released' => '',
    'Revenue' => '',
    'Runtime' => '',
    'Slug' => '',
    'Status' => '',
    'Tagline' => '',
    'The Movie is also available in <a href="{url}" title="{title}">{language}</a>' => '',
    'The Show is also available in <a href="{url}" title="{title}">{language}</a>' => '',
    'The movie could not be found!' => '',
    'The movie could not be loaded at the moment! Please try again later.' => '',
    'Title' => '',
    'Updated at' => '',
    'Vote count' => '',
    'Voting' => '',
    'Website' => '',
    'You have labeled the movie as watched again.' => '',
    'You have labeled the movie as watched. You can always click on the <em>watched again</em> button to track the movie multiple times.' => '',
    'You\'ve never seen the movie before!' => '',
    'themoviedb_id' => '',
    '{average}/10 ({count} Votes)' => '',
    '{job}: {name}' => '',
    '{name} as {character}' => '',
];
