<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Archive' => '',
    'Average vote' => '',
    'Backdrop path' => '',
    'Created at' => '',
    'Deleted at' => '',
    'Errow while syncing the show' => '',
    'First air date' => '',
    'First aired' => '',
    'Genres' => '',
    'Homepage' => '',
    'ID' => '',
    'In Production' => '',
    'In production' => '',
    'Language' => '',
    'Last air date' => '',
    'Last aired' => '',
    'Move to archive' => '',
    'Name' => '',
    'No' => '',
    'Original Name' => '',
    'Original Title' => '',
    'Original name' => '',
    'Overview' => '',
    'Popularity' => '',
    'Poster path' => '',
    'Restore' => '',
    'Restore from archive' => '',
    'Search for TV Shows/Movies/Actors' => '',
    'Show' => '',
    'Slug' => '',
    'Status' => '',
    'Staus' => '',
    'Subscribe' => '',
    'Successfully synced {0} shows as {1} seasons' => '',
    'Sync' => '',
    'Syncing...' => '',
    'The TV Show could not be found!' => '',
    'The TV Show could not be loaded at the moment! Please try again later.' => '',
    'The show could not be archived!' => '',
    'The show could not be unarchived!' => '',
    'The show is already archived!' => '',
    'The show is not archived!' => '',
    'TheMovieDB' => '',
    'Unsubscribe' => '',
    'Updated at' => '',
    'Vote count' => '',
    'Votes' => '',
    'Website' => '',
    'Yes' => '',
    'You are already subscribed to {name}.' => '',
    'You are not subscribed to {name}.' => '',
    'You successfully archived `{name}`. Move on to the <a href="{archive}">Archive</a> to see your archived shows.' => '',
    'You successfully unarchived `{name}`.' => '',
];
